<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>wheeltec_nav2</name>
  <version>1.0.0</version>
  <description>Nav2 navigation config for wheeltec differential drive robot</description>
  <maintainer email="wheeltec@example.com">wheeltec</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>wheeltec_chassis_cpp</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>nav2_behavior_tree</build_depend>
  <build_depend>nav2_behaviors</build_depend>
  <build_depend>nav2_core</build_depend>
  <build_depend>nav2_costmap_2d</build_depend>
  <build_depend>nav2_msgs</build_depend>
  <build_depend>nav2_util</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>pluginlib</build_depend>
  <build_depend>rclcpp</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>tf2</build_depend>
  <build_depend>behaviortree_cpp_v3</build_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav2_behavior_tree</exec_depend>
  <exec_depend>cartographer_ros_msgs</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>action_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>nav2_behaviors</exec_depend>
  <exec_depend>nav2_core</exec_depend>
  <exec_depend>nav2_costmap_2d</exec_depend>
  <exec_depend>nav2_util</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>pluginlib</exec_depend>
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>tf2</exec_depend>
  <exec_depend>wheeltec_chassis_cpp</exec_depend>
  <exec_depend>behaviortree_cpp_v3</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
    <nav2_core plugin="${prefix}/imu_behavior_plugin.xml" />
    <nav2_core plugin="${prefix}/controller_plugin.xml" />
  </export>
</package>
