// Generated by gencpp from file anorosdt/AnoRosGPS.msg
// DO NOT EDIT!


#ifndef ANOROSDT_MESSAGE_ANOROSGPS_H
#define ANOROSDT_MESSAGE_ANOROSGPS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace anorosdt
{
template <class ContainerAllocator>
struct AnoRosGPS_
{
  typedef AnoRosGPS_<ContainerAllocator> Type;

  AnoRosGPS_()
    : header()
    , FIX_STA(0)
    , S_NUM(0)
    , LNG(0)
    , LAT(0)
    , ALT_GPS(0)
    , N_SPE(0)
    , E_SPE(0)
    , D_SPE(0)
    , PDOP_001(0)
    , SACC_001(0)
    , VACC_001(0)  {
    }
  AnoRosGPS_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , FIX_STA(0)
    , S_NUM(0)
    , LNG(0)
    , LAT(0)
    , ALT_GPS(0)
    , N_SPE(0)
    , E_SPE(0)
    , D_SPE(0)
    , PDOP_001(0)
    , SACC_001(0)
    , VACC_001(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _FIX_STA_type;
  _FIX_STA_type FIX_STA;

   typedef uint8_t _S_NUM_type;
  _S_NUM_type S_NUM;

   typedef int32_t _LNG_type;
  _LNG_type LNG;

   typedef int32_t _LAT_type;
  _LAT_type LAT;

   typedef int32_t _ALT_GPS_type;
  _ALT_GPS_type ALT_GPS;

   typedef int16_t _N_SPE_type;
  _N_SPE_type N_SPE;

   typedef int16_t _E_SPE_type;
  _E_SPE_type E_SPE;

   typedef int16_t _D_SPE_type;
  _D_SPE_type D_SPE;

   typedef uint8_t _PDOP_001_type;
  _PDOP_001_type PDOP_001;

   typedef uint8_t _SACC_001_type;
  _SACC_001_type SACC_001;

   typedef uint8_t _VACC_001_type;
  _VACC_001_type VACC_001;





  typedef boost::shared_ptr< ::anorosdt::AnoRosGPS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anorosdt::AnoRosGPS_<ContainerAllocator> const> ConstPtr;

}; // struct AnoRosGPS_

typedef ::anorosdt::AnoRosGPS_<std::allocator<void> > AnoRosGPS;

typedef boost::shared_ptr< ::anorosdt::AnoRosGPS > AnoRosGPSPtr;
typedef boost::shared_ptr< ::anorosdt::AnoRosGPS const> AnoRosGPSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anorosdt::AnoRosGPS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anorosdt::AnoRosGPS_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anorosdt::AnoRosGPS_<ContainerAllocator1> & lhs, const ::anorosdt::AnoRosGPS_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.FIX_STA == rhs.FIX_STA &&
    lhs.S_NUM == rhs.S_NUM &&
    lhs.LNG == rhs.LNG &&
    lhs.LAT == rhs.LAT &&
    lhs.ALT_GPS == rhs.ALT_GPS &&
    lhs.N_SPE == rhs.N_SPE &&
    lhs.E_SPE == rhs.E_SPE &&
    lhs.D_SPE == rhs.D_SPE &&
    lhs.PDOP_001 == rhs.PDOP_001 &&
    lhs.SACC_001 == rhs.SACC_001 &&
    lhs.VACC_001 == rhs.VACC_001;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anorosdt::AnoRosGPS_<ContainerAllocator1> & lhs, const ::anorosdt::AnoRosGPS_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anorosdt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anorosdt::AnoRosGPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anorosdt::AnoRosGPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anorosdt::AnoRosGPS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anorosdt::AnoRosGPS_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anorosdt::AnoRosGPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anorosdt::AnoRosGPS_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anorosdt::AnoRosGPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f15bd0f1e86c4ad7d948709fb6dc242";
  }

  static const char* value(const ::anorosdt::AnoRosGPS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f15bd0f1e86c4adULL;
  static const uint64_t static_value2 = 0x7d948709fb6dc242ULL;
};

template<class ContainerAllocator>
struct DataType< ::anorosdt::AnoRosGPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anorosdt/AnoRosGPS";
  }

  static const char* value(const ::anorosdt::AnoRosGPS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anorosdt::AnoRosGPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 FIX_STA\n"
"uint8 S_NUM\n"
"int32 LNG\n"
"int32 LAT\n"
"int32 ALT_GPS\n"
"int16 N_SPE\n"
"int16 E_SPE\n"
"int16 D_SPE\n"
"uint8 PDOP_001\n"
"uint8 SACC_001\n"
"uint8 VACC_001\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::anorosdt::AnoRosGPS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anorosdt::AnoRosGPS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.FIX_STA);
      stream.next(m.S_NUM);
      stream.next(m.LNG);
      stream.next(m.LAT);
      stream.next(m.ALT_GPS);
      stream.next(m.N_SPE);
      stream.next(m.E_SPE);
      stream.next(m.D_SPE);
      stream.next(m.PDOP_001);
      stream.next(m.SACC_001);
      stream.next(m.VACC_001);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnoRosGPS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anorosdt::AnoRosGPS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anorosdt::AnoRosGPS_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "FIX_STA: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.FIX_STA);
    s << indent << "S_NUM: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.S_NUM);
    s << indent << "LNG: ";
    Printer<int32_t>::stream(s, indent + "  ", v.LNG);
    s << indent << "LAT: ";
    Printer<int32_t>::stream(s, indent + "  ", v.LAT);
    s << indent << "ALT_GPS: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ALT_GPS);
    s << indent << "N_SPE: ";
    Printer<int16_t>::stream(s, indent + "  ", v.N_SPE);
    s << indent << "E_SPE: ";
    Printer<int16_t>::stream(s, indent + "  ", v.E_SPE);
    s << indent << "D_SPE: ";
    Printer<int16_t>::stream(s, indent + "  ", v.D_SPE);
    s << indent << "PDOP_001: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.PDOP_001);
    s << indent << "SACC_001: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.SACC_001);
    s << indent << "VACC_001: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.VACC_001);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANOROSDT_MESSAGE_ANOROSGPS_H
